title: Robert Hoyt's AI Powered Cybersecurity Homelab Project 
description: A cybersecurtity homelab operating as an autommated AI-powered voice assisted SOC.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
